import type { Config } from "tailwindcss";
import animate from "tailwindcss-animate";

/**
 * Tailwind mapeado nas variáveis semânticas do design system Estudatta
 * (src/design/tokens.css). Nunca use hex direto nos componentes.
 */
const config: Config = {
  darkMode: ["selector", '[data-theme="dark"]'],
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    container: { center: true, padding: "var(--layout-gutter-mobile)", screens: { "2xl": "1200px" } },
    extend: {
      colors: {
        canvas: "var(--color-bg-canvas)",
        surface: "var(--color-bg-surface)",
        "surface-raised": "var(--color-bg-surface-raised)",
        inverse: "var(--color-bg-inverse)",
        primary: "var(--color-text-primary)",
        secondary: "var(--color-text-secondary)",
        tertiary: "var(--color-text-tertiary)",
        disabled: "var(--color-text-disabled)",
        "on-accent": "var(--color-text-on-accent)",
        border: "var(--color-border-default)",
        "border-subtle": "var(--color-border-subtle)",
        "border-strong": "var(--color-border-strong)",
        divider: "var(--color-divider)",
        accent: {
          DEFAULT: "var(--color-action-primary)",
          hover: "var(--color-action-primary-hover)",
          pressed: "var(--color-action-primary-pressed)",
          tint: "var(--color-action-primary-tint)",
          100: "var(--color-accent-100)",
          200: "var(--color-accent-200)",
          300: "var(--color-accent-300)",
          400: "var(--color-accent-400)",
          500: "var(--color-accent-500)",
          600: "var(--color-accent-600)",
          700: "var(--color-accent-700)",
          800: "var(--color-accent-800)",
          900: "var(--color-accent-900)",
        },
        neutral: {
          100: "var(--color-neutral-100)",
          200: "var(--color-neutral-200)",
          300: "var(--color-neutral-300)",
          400: "var(--color-neutral-400)",
          500: "var(--color-neutral-500)",
          600: "var(--color-neutral-600)",
          700: "var(--color-neutral-700)",
          800: "var(--color-neutral-800)",
          900: "var(--color-neutral-900)",
        },
        success: { DEFAULT: "var(--color-status-success)", tint: "var(--color-status-success-tint)" },
        warning: { DEFAULT: "var(--color-status-warning)", tint: "var(--color-status-warning-tint)" },
        pending: "var(--color-pending)",
        error: { DEFAULT: "var(--color-status-error)", tint: "var(--color-status-error-tint)" },
        info: { DEFAULT: "var(--color-status-info)", tint: "var(--color-status-info-tint)" },
        track: "var(--color-progress-track)",
        fill: "var(--color-progress-fill)",
        recovery: "var(--color-progress-recovery)",
        section: { DEFAULT: "var(--color-section)", glow: "var(--color-section-glow)" },
        // aliases shadcn
        background: "var(--color-bg-canvas)",
        foreground: "var(--color-text-primary)",
        card: "var(--color-bg-surface)",
        "card-foreground": "var(--color-text-primary)",
        popover: "var(--color-bg-surface-raised)",
        "popover-foreground": "var(--color-text-primary)",
        muted: "var(--color-bg-surface)",
        "muted-foreground": "var(--color-text-tertiary)",
        destructive: "var(--color-status-error)",
        input: "var(--color-border-default)",
        ring: "var(--color-action-focus)",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "-apple-system", "Segoe UI", "Roboto", "sans-serif"],
      },
      fontSize: {
        xs: ["11px", { lineHeight: "1.5" }],
        sm: ["13px", { lineHeight: "1.5" }],
        base: ["15px", { lineHeight: "1.55" }],
        md: ["15px", { lineHeight: "1.55" }],
        lg: ["17px", { lineHeight: "1.55" }],
        xl: ["20px", { lineHeight: "1.2" }],
        "2xl": ["25px", { lineHeight: "1.15", letterSpacing: "-0.015em" }],
        "3xl": ["32px", { lineHeight: "1.12", letterSpacing: "-0.015em" }],
        "4xl": ["42px", { lineHeight: "1.12", letterSpacing: "-0.015em" }],
        timer: ["64px", { lineHeight: "1", letterSpacing: "-0.02em" }],
        "timer-lg": ["96px", { lineHeight: "1", letterSpacing: "-0.02em" }],
      },
      spacing: {
        "ds-1": "var(--space-1)",
        "ds-2": "var(--space-2)",
        "ds-3": "var(--space-3)",
        "ds-4": "var(--space-4)",
        "ds-6": "var(--space-6)",
        "ds-8": "var(--space-8)",
        "ds-12": "var(--space-12)",
        "ds-16": "var(--space-16)",
        gutter: "var(--layout-gutter-mobile)",
        "gutter-lg": "var(--layout-gutter-desktop)",
        "bottom-nav": "var(--layout-bottom-nav-height)",
        sidebar: "var(--layout-sidebar-width)",
        touch: "44px",
      },
      borderRadius: {
        sm: "4px",
        DEFAULT: "8px",
        md: "8px",
        lg: "14px",
        xl: "14px",
        phone: "28px",
        full: "999px",
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        DEFAULT: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        "accent-ring": "0 0 0 1px var(--color-action-primary)",
        "inset-accent": "inset 0 0 0 1px var(--color-action-primary)",
        "inset-warning": "inset 0 0 0 1px var(--color-status-warning)",
        "inset-error": "inset 0 0 0 1px var(--color-status-error)",
        "inset-divider": "inset 0 0 0 1px var(--color-divider)",
      },
      transitionDuration: { fast: "120ms", base: "200ms", slow: "320ms" },
      transitionTimingFunction: { standard: "cubic-bezier(0.2, 0, 0, 1)" },
      maxWidth: { content: "1200px", reading: "58ch" },
      screens: { xs: "360px", tablet: "768px", desktop: "1024px" },
      keyframes: {
        spin: { to: { transform: "rotate(360deg)" } },
        "fade-in": { from: { opacity: "0" }, to: { opacity: "1" } },
        "slide-up": { from: { transform: "translateY(16px)", opacity: "0" }, to: { transform: "translateY(0)", opacity: "1" } },
      },
      animation: {
        spin: "spin 0.8s linear infinite",
        "fade-in": "fade-in 200ms cubic-bezier(0.2,0,0,1)",
        "slide-up": "slide-up 320ms cubic-bezier(0.2,0,0,1)",
      },
    },
  },
  plugins: [animate],
};

export default config;
