"""activity language

Revision ID: a67070e5120a
Revises: 7e723a2e8e02
Create Date: 2026-09-19 16:08:02.551508+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'a67070e5120a'
down_revision = '7e723a2e8e02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('language', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###
    # "Inglês" vira a categoria Idiomas com o inglês escolhido. "Outro idioma" antigo não dizia
    # qual idioma: fica como "und" (Outro idioma) até a pessoa escolher.
    op.execute(
        "UPDATE activities SET category = 'idioma', language = 'en' WHERE category = 'ingles'"
    )
    op.execute(
        "UPDATE activities SET language = 'und' WHERE category = 'idioma' AND language IS NULL"
    )


def downgrade() -> None:
    op.execute(
        "UPDATE activities SET category = 'ingles' WHERE category = 'idioma' AND language = 'en'"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'language')
    # ### end Alembic commands ###
