"""user avatars

Revision ID: 351f195e0969
Revises: c2ea232ad278
Create Date: 2026-09-20 15:57:51.129915+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '351f195e0969'
down_revision = 'c2ea232ad278'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_avatars',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_avatars')
    # ### end Alembic commands ###
