"""current material and page bookmark

Revision ID: fcb3826ad7ed
Revises: a9b351496206
Create Date: 2026-09-20 23:17:58.204893+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'fcb3826ad7ed'
down_revision = 'a9b351496206'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('current_material_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'activities', 'materials', ['current_material_id'], ['id'], ondelete='SET NULL')
    op.add_column('materials', sa.Column('current_page', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'current_page')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_column('activities', 'current_material_id')
    # ### end Alembic commands ###
