"""reengagement prefs

Revision ID: c2ea232ad278
Revises: a3c4b604a768
Create Date: 2026-09-19 17:56:03.778816+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'c2ea232ad278'
down_revision = 'a3c4b604a768'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_preferences', sa.Column('reengagement', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('notification_preferences', sa.Column('reengagement_email', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_preferences', 'reengagement_email')
    op.drop_column('notification_preferences', 'reengagement')
    # ### end Alembic commands ###
