"""study types, revisions, mock exams, gamification

Revision ID: 7e723a2e8e02
Revises: a9e53591113d
Create Date: 2026-09-19 01:06:51.776413+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '7e723a2e8e02'
down_revision = 'a9e53591113d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_achievements',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'code', name='uq_user_achievement')
    )
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.create_table('xp_events',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('dedupe_key', sa.String(length=120), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dedupe_key', name='uq_xp_user_dedupe')
    )
    op.create_index(op.f('ix_xp_events_user_id'), 'xp_events', ['user_id'], unique=False)
    op.create_table('mock_exams',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('taken_on', sa.Date(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mock_exams_activity_date', 'mock_exams', ['activity_id', 'taken_on'], unique=False)
    op.create_index(op.f('ix_mock_exams_activity_id'), 'mock_exams', ['activity_id'], unique=False)
    op.create_index(op.f('ix_mock_exams_user_id'), 'mock_exams', ['user_id'], unique=False)
    op.create_table('mock_exam_subjects',
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('subject_title', sa.String(length=160), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['mock_exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_exam_subjects_exam_id'), 'mock_exam_subjects', ['exam_id'], unique=False)
    op.create_table('revisions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('topic_id', sa.Uuid(), nullable=True),
    sa.Column('source_session_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('done_session_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['done_session_id'], ['study_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_session_id'], ['study_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_session_id', 'step', name='uq_revision_source_step')
    )
    op.create_index(op.f('ix_revisions_activity_id'), 'revisions', ['activity_id'], unique=False)
    op.create_index('ix_revisions_user_due', 'revisions', ['user_id', 'status', 'due_date'], unique=False)
    op.create_index(op.f('ix_revisions_user_id'), 'revisions', ['user_id'], unique=False)
    op.add_column('activities', sa.Column('weekly_questions_goal', sa.Integer(), nullable=True))
    op.add_column('activities', sa.Column('weekly_pages_goal', sa.Integer(), nullable=True))
    op.add_column('study_sessions', sa.Column('study_type', sa.String(length=16), server_default='teoria', nullable=False))
    op.add_column('study_sessions', sa.Column('questions_total', sa.Integer(), nullable=True))
    op.add_column('study_sessions', sa.Column('questions_correct', sa.Integer(), nullable=True))
    op.add_column('subjects', sa.Column('weight', sa.Integer(), server_default='1', nullable=False))
    op.add_column('subjects', sa.Column('difficulty', sa.String(length=8), server_default='media', nullable=False))
    op.add_column('user_preferences', sa.Column('revisions_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('user_preferences', sa.Column('revision_intervals', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='[1, 7, 30]', nullable=False))
    op.add_column('user_preferences', sa.Column('mascot_enabled', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'mascot_enabled')
    op.drop_column('user_preferences', 'revision_intervals')
    op.drop_column('user_preferences', 'revisions_enabled')
    op.drop_column('subjects', 'difficulty')
    op.drop_column('subjects', 'weight')
    op.drop_column('study_sessions', 'questions_correct')
    op.drop_column('study_sessions', 'questions_total')
    op.drop_column('study_sessions', 'study_type')
    op.drop_column('activities', 'weekly_pages_goal')
    op.drop_column('activities', 'weekly_questions_goal')
    op.drop_index(op.f('ix_revisions_user_id'), table_name='revisions')
    op.drop_index('ix_revisions_user_due', table_name='revisions')
    op.drop_index(op.f('ix_revisions_activity_id'), table_name='revisions')
    op.drop_table('revisions')
    op.drop_index(op.f('ix_mock_exam_subjects_exam_id'), table_name='mock_exam_subjects')
    op.drop_table('mock_exam_subjects')
    op.drop_index(op.f('ix_mock_exams_user_id'), table_name='mock_exams')
    op.drop_index(op.f('ix_mock_exams_activity_id'), table_name='mock_exams')
    op.drop_index('ix_mock_exams_activity_date', table_name='mock_exams')
    op.drop_table('mock_exams')
    op.drop_index(op.f('ix_xp_events_user_id'), table_name='xp_events')
    op.drop_table('xp_events')
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    # ### end Alembic commands ###
